### PR TITLE
Better escaping

### PR DESCRIPTION
**Pull request by 0joshuaolson1**
Fixes https://github.com/Picolab/pico-engine/issues/283 and https://github.com/Picolab/pico-engine/issues/284.

Escape `#{` in a chevron with `\#{`. Put `\#{` in a chevron with `\\#{`.

Escape `>>` in a chevron with `>\>`, `\>>`, or `\>\>` (recommended). I recommend putting `\>` in a chevron with `\\\>` (but `\\>` works in some cases). Escape any number of `>`s at the end of a chevron like:
- 1:
  - `<<\>>>`
- 2:
  - `<<>\>>>`
  - `<<\>\>>>` (to document as recommended)
- 3:
  - `<<\>>\>>>`
  - `<<>\>\>>>`
  - `<<\>\>\>>>` (to document as recommended)

### CODE REVIEW

**Comment by farskipper** [comment]
Looks good, I just started some tests at the end of `tests/parser.test.js` for escaping.

If you could add some assertions there for the changes you made, then I think we're good to merge it.

**Comment by 0joshuaolson1** [comment]
How's these tests? Thanks for starting them.

This is a particularly annoying case of wishing single-quotes strings were allowed...

**Comment by farskipper** [comment]
Looks good. Yeah, eslint is actually configured to let you use single quotes only if you are avoiding escaping quotes: http://eslint.org/docs/rules/quotes#avoidescape and https://github.com/Picolab/node-krl-parser/blob/master/.eslintrc.js#L11

**Comment by 0joshuaolson1** [comment]
Do all linters have the idea that double-quoted strings are better style/not more difficult to type/read? o_o'

**Comment by farskipper** [comment]
I don't know, but I just prefer uniformity to saving keystrokes. And it's the rule I use on all my projects now. The reason I pick double by default is the consistency with json, other languages, and a stronger visual cue. And I also find it more common that I use apostrophes in strings rather than double quotes. I.e. doing a grep search for a sentence containing `it's` is easier to not think about the potential of escaping the apostrophe.

But I really don't care _that_ much about it, so you can turn it off if you really want to :)

**Comment by 0joshuaolson1** [comment]
Fair.

**Pull request merged**
